/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

class TiDial {
    val greeting: String
        get() {
            return "Hello world."
        }
    fun greet(): String {
	    return "Hello world."
    }
}

fun main(args: Array<String>) {
    println(TiDial().greeting)
    println(TiDial().greet())

}
